name: call-reutilizar
on:
  push:
    branches:
      - main
jobs:
  call-worflow-remote-repo:
    uses: televisa-digital/orb-npm-publish/.github/workflows/action-npm-publish.yml@feat(JMC)
    with:
      reponame: "orcaslide"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_NEW }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}