name: call-reutilizar
on:
  push:
    branches:
      - main
jobs:
  call-worflow-remote-repo:
    uses: dummy-git-actions/actions-reutility/.github/workflows/reutilizar.yml@main
    with:
      username: git@github.com:OrcaSlide/orcaslide.git
    secrets:
      NPM_TOKEN: "${{secrets.NPM_TOKEN}}"
